### ISSUE TITLE
Update mínt if installed

### ISSUE THREAD

**Issue by anissen** [underscorediscovery/snowfall#7]
It would be nice if `snowfall` could automatically update mint if it's installed. Alternatively provide a `snowfall update luxe --mint` or `snowfall update mint` command.

**Comment by underscorediscovery** [comment]
This is outside the purpose of the tool as it stands! mint is standalone, not a dependency nor is it required and inversely, luxe is not required to use mint either. It doesn't make sense for snowfall to try and account for it to me because the same can be said for any number of random libraries, and there is haxelib or git for that.

I really do understand the motivation, it's just that for the purposes and use case of this tool I won't be adding tertiary libraries for now. Thanks for the suggestion!
